// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShopSystem.Data.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public string Brand { get; set; }

    public string Diamond { get; set; }

    public string Image { get; set; }

    public double? Price { get; set; }

    public int? Quantity { get; set; }

    public string Description { get; set; }

    public bool? Status { get; set; }

    public int? Size { get; set; }

    public int? CategoryId { get; set; }

    public virtual Category Category { get; set; }
}